<a href="https://colab.research.google.com/github/bheanne/LinearAlgebra/blob/main/LAB%20REPORT%207/Marq_Lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Task 1***

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

S = np.array([[12, 30, 95, 19], [19, 94, 1, 6], [18, 27, 36, 45], [54, 63, 72, 81]])
E = np.array([[9, 7, 9, 7], [9, 7, 9, 9], [7, 9, 9, 7], [7, 7, 7, 9]])
O = np.array([[5, 12, 45, 11], [22, 33, 44, 55], [66, 77, 88, 99], [24, 36, 48, 60]])
K = np.array([[9, 8, 6, 2], [3, 6, 5, 4], [1, 4, 3, 6], [4, 8, 6, 10]])
J = np.identity(5)
I = np.ones([4, 4])
N = np.array([[11, 21, 20, 0, 4], [1, 25, 19, 96, 5] , [90, 76, 58, 4, 6], [15, 1, 7, 14, 8], [1, 8, 15, 22, 29]])
V = np.zeros([5,5])

print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
print('\nShapes:')
print('The Shape of S is', S.shape)
print('The Shape of E is', E.shape)
print('The Shape of O is', O.shape)
print('The Shape of K is', K.shape)
print('The Shape of J is', J.shape)
print('The Shape of I is', I.shape)
print('The Shape of N is', N.shape)
print('The Shape of V is', V.shape)
print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Shapes:
The Shape of S is (4, 4)
The Shape of E is (4, 4)
The Shape of O is (4, 4)
The Shape of K is (4, 4)
The Shape of J is (5, 5)
The Shape of I is (4, 4)
The Shape of N is (5, 5)
The Shape of V is (5, 5)

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Commutative(MatrixE,MatrixI):
  Comm_EI = np.dot(E, I)
  Comm_IE = np.dot(I, E)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nCommutative Property: ')
  print(Comm_EI)
  print('\nis not equal to')
  print('\n')
  print(Comm_IE)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  
Commutative(E, I)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Commutative Property: 
[[32. 32. 32. 32.]
 [34. 34. 34. 34.]
 [32. 32. 32. 32.]
 [30. 30. 30. 30.]]

is not equal to


[[32. 30. 34. 32.]
 [32. 30. 34. 32.]
 [32. 30. 34. 32.]
 [32. 30. 34. 32.]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Associative(MatrixK,MatrixO,MatrixS):
  Asso_SK = np.dot(S, K)
  Asso_SKO = np.dot(Asso_SK, O)
  Asso_KO = np.dot(K, O)
  Asso_SOK = np.dot(S, Asso_KO)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nAssociative Property: ')
  print(Asso_SKO)
  print('\nis equal to')
  print('\n')
  print(Asso_SOK)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  
Associative(K, O, S)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Associative Property: 
[[ 82303 111453 150197 164218]
 [ 71924  96331 133166 137975]
 [ 80541 109215 149823 159678]
 [170721 231399 319923 336690]]

is equal to


[[ 82303 111453 150197 164218]
 [ 71924  96331 133166 137975]
 [ 80541 109215 149823 159678]
 [170721 231399 319923 336690]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Distributive(MatrixJ,MatrixV,MatrixN):
  Distri_JV = np.add(J, V)
  Distri_JVN = np.dot(N, Distri_JV)
  Distri_NV = np.dot(N, V)
  Distri_JN = np.dot(J, N)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nDistribute Property #1: ')
  print(Distri_JVN)
  print('\nis equal to')
  print('\n')
  print(Distri_NV + Distri_JN)

  Distri_NVJ = np.dot(Distri_NV, J)
  Distri_VN = np.dot(V, N)
  Distri_JJ = np.dot(J, J)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nDistribute Property #2: ')
  print(Distri_NVJ)
  print('\nis not equal to')
  print('\n')
  print(Distri_VN + Distri_JJ)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")

Distributive(J, V, N)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Distribute Property #1: 
[[11. 21. 20.  0.  4.]
 [ 1. 25. 19. 96.  5.]
 [90. 76. 58.  4.  6.]
 [15.  1.  7. 14.  8.]
 [ 1.  8. 15. 22. 29.]]

is equal to


[[11. 21. 20.  0.  4.]
 [ 1. 25. 19. 96.  5.]
 [90. 76. 58.  4.  6.]
 [15.  1.  7. 14.  8.]
 [ 1.  8. 15. 22. 29.]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Distribute Property #2: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

is not equal to


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Identity(MatrixJ,MatrixN):
  IdentJN = np.dot(MatrixJ, MatrixN)
  IdentNJ = np.dot(MatrixN, MatrixJ)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nIdentity Property: ')
  print(IdentJN)
  print('\nis equal to')
  print('\n')
  print(IdentNJ)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  
Identity(N, J)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Identity Property: 
[[11. 21. 20.  0.  4.]
 [ 1. 25. 19. 96.  5.]
 [90. 76. 58.  4.  6.]
 [15.  1.  7. 14.  8.]
 [ 1.  8. 15. 22. 29.]]

is equal to


[[11. 21. 20.  0.  4.]
 [ 1. 25. 19. 96.  5.]
 [90. 76. 58.  4.  6.]
 [15.  1.  7. 14.  8.]
 [ 1.  8. 15. 22. 29.]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Zero(MatrixV,MatrixJ):
  Zero0VJ = np.dot(MatrixV, MatrixJ)
  Zero0JV = np.dot(MatrixJ, MatrixV)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nZero Property:')
  print(Zero0VJ)
  print('\nis equal to')
  print('\n')
  print(Zero0JV)
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")

Zero(V, J)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Zero Property:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

is equal to


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹


In [ ]:
def Dimension(MatrixE,MatrixO):
  MatrixE.shape[0]
  MatrixO.shape[1]
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")
  print('\nDimension Property: ')
  print(MatrixE[0], MatrixO[1])
  print("\n⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹")

Dimension(E, O)


⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹

Dimension Property: 
[9 7 9 7] [22 33 44 55]

⊹˙⋆°••°⋆˙⊹•°⋆˙✭˙⋆°•⊹˙⋆°•⊹˙⋆°••°⋆˙⊹
